"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Activity,
  AlertTriangle,
  BarChart3,
  CheckCircle2,
  Database,
  Gauge,
  History,
  RefreshCw,
  ShieldAlert,
  ShieldCheck,
  TrendingDown,
  TrendingUp,
  Info,
} from "lucide-react";

import { apiFetch } from "@/app/lib/api";

type Snapshot = {
  id: number;
  snapshot_at: string;
  period_start: string | null;
  period_end: string | null;

  uee_score: number;
  compliance_health_index: number;

  risk_index: number;
  coverage_index: number;
  maturity_index: number;
  evidence_index: number;
  task_pressure_index: number;

  risk_count: number;
  control_count: number;
  evidence_count: number;

  data_quality_score: number | null;

  source: string;
  engine_version: string | null;
};

type Comparison = {
  current: number | null;
  previous: number | null;
  delta: number | null;
  direction:
    | "improved"
    | "deteriorated"
    | "unchanged"
    | "insufficient_data";
  sufficient_data: boolean;
};

type Summary = {
  tenant_id: number;
  latest: Snapshot | null;
  comparison: Comparison;
  historical_snapshot_count: number;
  peer_benchmark_available: boolean;
  peer_benchmark_reason: string | null;
};

const componentMeta = [
  {
    key: "risk_index",
    label: "Risk Exposure",
    description: "Aggregate exposure generated by the tenant risk population.",
    icon: ShieldAlert,
  },
  {
    key: "coverage_index",
    label: "Control Coverage",
    description: "Exposure caused by controls that are not adequately covered.",
    icon: ShieldCheck,
  },
  {
    key: "maturity_index",
    label: "Maturity Exposure",
    description: "Exposure associated with the current maturity assessment.",
    icon: Gauge,
  },
  {
    key: "evidence_index",
    label: "Evidence Exposure",
    description: "Exposure associated with evidence quality and approval state.",
    icon: Database,
  },
  {
    key: "task_pressure_index",
    label: "Task Pressure",
    description: "Operational pressure from open compliance tasks.",
    icon: Activity,
  },
] as const;

function formatNumber(value: number | null | undefined, digits = 2) {
  if (value === null || value === undefined || Number.isNaN(value)) {
    return "—";
  }

  return value.toFixed(digits);
}

function formatDate(value: string | null | undefined) {
  if (!value) return "—";

  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

function exposureLabel(value: number) {
  if (value < 25) return "Low";
  if (value < 50) return "Moderate";
  if (value < 75) return "High";
  return "Critical";
}

function healthLabel(value: number) {
  if (value >= 75) return "Healthy";
  if (value >= 50) return "Watch";
  return "Critical";
}

function directionLabel(direction: Comparison["direction"]) {
  switch (direction) {
    case "improved":
      return "Improved";
    case "deteriorated":
      return "Deteriorated";
    case "unchanged":
      return "Unchanged";
    default:
      return "Insufficient data";
  }
}

function DirectionIcon({
  direction,
}: {
  direction: Comparison["direction"];
}) {
  if (direction === "improved") {
    return <TrendingDown size={15} />;
  }

  if (direction === "deteriorated") {
    return <TrendingUp size={15} />;
  }

  if (direction === "unchanged") {
    return <Activity size={15} />;
  }

  return <Info size={15} />;
}

export default function BenchmarkingPage() {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [history, setHistory] = useState<Snapshot[]>([]);

  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [capturing, setCapturing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadData = useCallback(async () => {
    try {
      setError(null);

      const [summaryRes, historyRes] = await Promise.all([
        apiFetch("/benchmarking/summary"),
        apiFetch("/benchmarking/history?limit=30"),
      ]);

      if (!summaryRes.ok) {
        throw new Error(
          `Benchmark summary failed (${summaryRes.status})`
        );
      }

      if (!historyRes.ok) {
        throw new Error(
          `Benchmark history failed (${historyRes.status})`
        );
      }

      const summaryJson = await summaryRes.json();
      const historyJson = await historyRes.json();

      setSummary(summaryJson);
      setHistory(Array.isArray(historyJson) ? historyJson : []);
    } catch (err) {
      console.error(err);

      setError(
        err instanceof Error
          ? err.message
          : "Benchmarking could not be loaded."
      );
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    void loadData();
  }, [loadData]);

  async function refresh() {
    setRefreshing(true);
    await loadData();
  }

  async function captureSnapshot() {
    try {
      setCapturing(true);
      setError(null);

      const response = await apiFetch("/benchmarking/snapshot", {
        method: "POST",
      });

      if (!response.ok) {
        const text = await response.text();

        throw new Error(
          text || `Snapshot capture failed (${response.status})`
        );
      }

      await loadData();
    } catch (err) {
      console.error(err);

      setError(
        err instanceof Error
          ? err.message
          : "Benchmark snapshot could not be captured."
      );
    } finally {
      setCapturing(false);
    }
  }

  const latest = summary?.latest ?? null;
  const comparison = summary?.comparison;

  const componentRows = useMemo(() => {
    if (!latest) return [];

    return componentMeta.map((component) => ({
      ...component,
      value: Number(latest[component.key]),
    }));
  }, [latest]);

  if (loading) {
    return (
      <div className="flex min-h-[70vh] items-center justify-center">
        <div className="flex items-center gap-3 text-sm text-slate-500">
          <RefreshCw size={17} className="animate-spin" />
          Loading enterprise benchmarking...
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 pb-10">
      <header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">
            <BarChart3 size={15} />
            Intelligence / Benchmarking
          </div>

          <h1 className="text-2xl font-semibold tracking-tight text-slate-900">
            Enterprise Benchmarking
          </h1>

          <p className="mt-1 max-w-3xl text-sm leading-6 text-slate-500">
            Historical performance benchmarking based on persisted,
            tenant-scoped UEE observations.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={refresh}
            disabled={refreshing}
            className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700 shadow-sm transition hover:bg-slate-50 disabled:opacity-50"
          >
            <RefreshCw
              size={15}
              className={refreshing ? "animate-spin" : ""}
            />
            Refresh
          </button>

          <button
            type="button"
            onClick={captureSnapshot}
            disabled={capturing}
            className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white shadow-sm transition hover:bg-slate-800 disabled:opacity-50"
          >
            <History size={15} />
            {capturing ? "Capturing..." : "Capture Snapshot"}
          </button>
        </div>
      </header>

      {error && (
        <div className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
          <AlertTriangle size={18} className="mt-0.5 shrink-0" />
          <div>
            <div className="font-semibold">Benchmarking error</div>
            <div className="mt-1">{error}</div>
          </div>
        </div>
      )}

      {!latest ? (
        <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center shadow-sm">
          <History
            size={30}
            className="mx-auto text-slate-400"
          />

          <h2 className="mt-4 text-lg font-semibold text-slate-900">
            No benchmark snapshot available
          </h2>

          <p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">
            Capture the first UEE snapshot to establish the tenant's
            benchmark baseline.
          </p>

          <button
            type="button"
            onClick={captureSnapshot}
            disabled={capturing}
            className="mt-5 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
          >
            {capturing ? "Capturing..." : "Capture Baseline Snapshot"}
          </button>
        </div>
      ) : (
        <>
          <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <MetricCard
              title="Unified Exposure Score"
              value={formatNumber(latest.uee_score)}
              subtitle={exposureLabel(latest.uee_score)}
              icon={<ShieldAlert size={18} />}
            />

            <MetricCard
              title="Compliance Health"
              value={`${formatNumber(latest.compliance_health_index)}/100`}
              subtitle={healthLabel(latest.compliance_health_index)}
              icon={<ShieldCheck size={18} />}
            />

            <MetricCard
              title="Data Quality"
              value={
                latest.data_quality_score === null
                  ? "—"
                  : formatNumber(latest.data_quality_score)
              }
              subtitle={
                latest.data_quality_score === null
                  ? "Not available"
                  : "Source confidence indicator"
              }
              icon={<Database size={18} />}
            />

            <MetricCard
              title="Historical Snapshots"
              value={String(
                summary?.historical_snapshot_count ?? 0
              )}
              subtitle={
                summary?.historical_snapshot_count === 1
                  ? "Baseline established"
                  : "Persisted observations"
              }
              icon={<History size={18} />}
            />
          </section>

          <section className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]">
            <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
              <div className="border-b border-slate-100 px-5 py-4">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <h2 className="font-semibold text-slate-900">
                      UEE Component Benchmark
                    </h2>
                    <p className="mt-1 text-xs text-slate-500">
                      All component values use the UEE exposure convention:
                      0 = best, 100 = worst.
                    </p>
                  </div>

                  <div className="rounded-lg bg-slate-50 px-3 py-2 text-right">
                    <div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">
                      Engine
                    </div>
                    <div className="mt-0.5 text-xs font-semibold text-slate-700">
                      {latest.engine_version ?? "—"}
                    </div>
                  </div>
                </div>
              </div>

              <div className="divide-y divide-slate-100">
                {componentRows.map((row) => {
                  const Icon = row.icon;

                  return (
                    <div
                      key={row.key}
                      className="px-5 py-4"
                    >
                      <div className="flex items-start gap-4">
                        <div className="mt-0.5 rounded-lg bg-slate-100 p-2 text-slate-600">
                          <Icon size={16} />
                        </div>

                        <div className="min-w-0 flex-1">
                          <div className="flex items-center justify-between gap-4">
                            <div>
                              <div className="text-sm font-semibold text-slate-800">
                                {row.label}
                              </div>
                              <div className="mt-0.5 text-xs text-slate-500">
                                {row.description}
                              </div>
                            </div>

                            <div className="text-right">
                              <div className="text-lg font-semibold text-slate-900">
                                {formatNumber(row.value)}
                              </div>
                              <div className="text-[11px] font-medium text-slate-500">
                                {row.key === "maturity_index" &&
                                row.value === 0 &&
                                history.length > 0
                                  ? "Not assessed / no exposure"
                                  : exposureLabel(row.value)}
                              </div>
                            </div>
                          </div>

                          <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100">
                            <div
                              className="h-full rounded-full bg-slate-700 transition-all"
                              style={{
                                width: `${Math.max(
                                  0,
                                  Math.min(100, row.value)
                                )}%`,
                              }}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
              <div className="border-b border-slate-100 px-5 py-4">
                <h2 className="font-semibold text-slate-900">
                  Current vs Previous
                </h2>
                <p className="mt-1 text-xs text-slate-500">
                  Comparison is calculated only from persisted snapshots.
                </p>
              </div>

              <div className="p-5">
                <div className="rounded-xl border border-slate-200 bg-slate-50 p-5">
                  <div className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                    UEE Score
                  </div>

                  <div className="mt-2 flex items-end justify-between gap-4">
                    <div className="text-3xl font-semibold text-slate-900">
                      {formatNumber(comparison?.current)}
                    </div>

                    {comparison && (
                      <div
                        className={`flex items-center gap-1 rounded-lg px-2.5 py-1.5 text-xs font-semibold ${
                          comparison.direction === "improved"
                            ? "bg-emerald-50 text-emerald-700"
                            : comparison.direction === "deteriorated"
                              ? "bg-red-50 text-red-700"
                              : "bg-slate-100 text-slate-600"
                        }`}
                      >
                        <DirectionIcon
                          direction={comparison.direction}
                        />
                        {directionLabel(comparison.direction)}
                      </div>
                    )}
                  </div>

                  <div className="mt-4 grid grid-cols-2 gap-3">
                    <SmallStat
                      label="Previous"
                      value={formatNumber(
                        comparison?.previous
                      )}
                    />

                    <SmallStat
                      label="Delta"
                      value={formatNumber(comparison?.delta)}
                    />
                  </div>
                </div>

                {!comparison?.sufficient_data && (
                  <div className="mt-4 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-800">
                    <Info size={16} className="mt-0.5 shrink-0" />
                    <div>
                      <div className="font-semibold">
                        Historical comparison unavailable
                      </div>
                      <div className="mt-1">
                        At least two persisted benchmark snapshots are
                        required before a delta can be calculated.
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </section>

          <section className="grid gap-6 xl:grid-cols-[0.7fr_1.3fr]">
            <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
              <div className="border-b border-slate-100 px-5 py-4">
                <h2 className="font-semibold text-slate-900">
                  Peer Benchmark
                </h2>
              </div>

              <div className="p-5">
                <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5">
                  <div className="flex items-start gap-3">
                    <BarChart3
                      size={18}
                      className="mt-0.5 text-slate-500"
                    />

                    <div>
                      <div className="text-sm font-semibold text-slate-800">
                        Peer comparison unavailable
                      </div>

                      <p className="mt-1 text-xs leading-5 text-slate-500">
                        {summary?.peer_benchmark_reason ??
                          "No peer benchmark population is configured."}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
              <div className="border-b border-slate-100 px-5 py-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="font-semibold text-slate-900">
                      Historical Observations
                    </h2>
                    <p className="mt-1 text-xs text-slate-500">
                      Latest persisted benchmark snapshots.
                    </p>
                  </div>

                  <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">
                    {history.length} loaded
                  </span>
                </div>
              </div>

              {history.length === 0 ? (
                <div className="p-8 text-center text-sm text-slate-500">
                  No historical observations available.
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-sm">
                    <thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400">
                      <tr>
                        <th className="px-5 py-3 font-semibold">
                          Snapshot
                        </th>
                        <th className="px-5 py-3 font-semibold">
                          UEE
                        </th>
                        <th className="px-5 py-3 font-semibold">
                          Health
                        </th>
                        <th className="px-5 py-3 font-semibold">
                          Risk
                        </th>
                        <th className="px-5 py-3 font-semibold">
                          Coverage
                        </th>
                        <th className="px-5 py-3 font-semibold">
                          Quality
                        </th>
                      </tr>
                    </thead>

                    <tbody className="divide-y divide-slate-100">
                      {history.map((snapshot) => (
                        <tr
                          key={snapshot.id}
                          className="hover:bg-slate-50"
                        >
                          <td className="px-5 py-3">
                            <div className="font-medium text-slate-800">
                              #{snapshot.id}
                            </div>
                            <div className="mt-0.5 text-xs text-slate-400">
                              {formatDate(
                                snapshot.snapshot_at
                              )}
                            </div>
                          </td>

                          <td className="px-5 py-3 font-semibold text-slate-800">
                            {formatNumber(snapshot.uee_score)}
                          </td>

                          <td className="px-5 py-3 text-slate-700">
                            {formatNumber(
                              snapshot.compliance_health_index
                            )}
                          </td>

                          <td className="px-5 py-3 text-slate-700">
                            {formatNumber(snapshot.risk_index)}
                          </td>

                          <td className="px-5 py-3 text-slate-700">
                            {formatNumber(
                              snapshot.coverage_index
                            )}
                          </td>

                          <td className="px-5 py-3 text-slate-700">
                            {snapshot.data_quality_score ===
                            null
                              ? "—"
                              : formatNumber(
                                  snapshot.data_quality_score
                                )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </section>

          <section className="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="border-b border-slate-100 px-5 py-4">
              <h2 className="font-semibold text-slate-900">
                Benchmark Traceability
              </h2>
              <p className="mt-1 text-xs text-slate-500">
                Provenance and source-population information for the
                current observation.
              </p>
            </div>

            <div className="grid gap-px bg-slate-100 md:grid-cols-3 lg:grid-cols-6">
              <TraceItem
                label="Snapshot"
                value={formatDate(latest.snapshot_at)}
              />

              <TraceItem
                label="Source"
                value={latest.source}
              />

              <TraceItem
                label="Engine"
                value={latest.engine_version ?? "—"}
              />

              <TraceItem
                label="Risks"
                value={String(latest.risk_count)}
              />

              <TraceItem
                label="Controls"
                value={String(latest.control_count)}
              />

              <TraceItem
                label="Evidence Files"
                value={String(latest.evidence_count)}
              />
            </div>
          </section>
        </>
      )}
    </div>
  );
}

function MetricCard({
  title,
  value,
  subtitle,
  icon,
}: {
  title: string;
  value: string;
  subtitle: string;
  icon: React.ReactNode;
}) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex items-center justify-between">
        <div className="rounded-lg bg-slate-100 p-2 text-slate-600">
          {icon}
        </div>

        <CheckCircle2 size={15} className="text-slate-300" />
      </div>

      <div className="mt-5 text-xs font-semibold uppercase tracking-wider text-slate-400">
        {title}
      </div>

      <div className="mt-1 text-2xl font-semibold tracking-tight text-slate-900">
        {value}
      </div>

      <div className="mt-1 text-xs font-medium text-slate-500">
        {subtitle}
      </div>
    </div>
  );
}

function SmallStat({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-lg border border-slate-200 bg-white p-3">
      <div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">
        {label}
      </div>

      <div className="mt-1 text-sm font-semibold text-slate-800">
        {value}
      </div>
    </div>
  );
}

function TraceItem({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="bg-white px-5 py-4">
      <div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">
        {label}
      </div>

      <div className="mt-1 truncate text-xs font-semibold text-slate-700">
        {value}
      </div>
    </div>
  );
}

