from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Optional


class NotificationEventType:
    TASK_CREATED = "TASK_CREATED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_OVERDUE = "TASK_OVERDUE"

    FINDING_CREATED = "FINDING_CREATED"
    FINDING_ASSIGNED = "FINDING_ASSIGNED"
    FINDING_SUBMITTED_FOR_REVIEW = "FINDING_SUBMITTED_FOR_REVIEW"
    FINDING_PLAN_APPROVED = "FINDING_PLAN_APPROVED"
    FINDING_REVISION_REQUIRED = "FINDING_REVISION_REQUIRED"
    FINDING_IMPLEMENTATION_COMPLETED = "FINDING_IMPLEMENTATION_COMPLETED"
    FINDING_VERIFICATION_FAILED = "FINDING_VERIFICATION_FAILED"
    FINDING_CLOSED = "FINDING_CLOSED"

    RISK_CREATED = "RISK_CREATED"
    RISK_UPDATED = "RISK_UPDATED"
    RISK_ASSESSED = "RISK_ASSESSED"
    RISK_SCORE_CHANGED = "RISK_SCORE_CHANGED"
    RISK_ESCALATED = "RISK_ESCALATED"

    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    EVIDENCE_SUBMITTED_FOR_REVIEW = "EVIDENCE_SUBMITTED_FOR_REVIEW"
    EVIDENCE_APPROVED = "EVIDENCE_APPROVED"
    EVIDENCE_REJECTED = "EVIDENCE_REJECTED"
    EVIDENCE_ROLLED_BACK = "EVIDENCE_ROLLED_BACK"
    EVIDENCE_REVIEW_OVERDUE = "EVIDENCE_REVIEW_OVERDUE"

    TASK_SYNCED_TO_JIRA = "TASK_SYNCED_TO_JIRA"
    TASK_SYNCED_TO_CLICKUP = "TASK_SYNCED_TO_CLICKUP"
    TASK_SYNC_FAILED = "TASK_SYNC_FAILED"


class NotificationCategory:
    SYSTEM = "SYSTEM"
    COMPLIANCE = "COMPLIANCE"
    RISK = "RISK"
    AUDIT = "AUDIT"
    TASK = "TASK"
    EVIDENCE = "EVIDENCE"
    INTEGRATION = "INTEGRATION"
    SECURITY = "SECURITY"


class NotificationSeverity:
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass(frozen=True)
class NotificationEvent:
    event_type: str
    category: str
    tenant_id: int
    actor_user_id: Optional[int]
    entity_type: str
    entity_id: int
    title: str
    message: str
    payload: Dict[str, Any] = field(default_factory=dict)
